### ISSUE TITLE
Update Bblfsh playground

### ISSUE THREAD

**Issue by bzz** [src-d/okrs#56]
**Parent objective:**  #12
**Progress:** 0%

- [x] [P0] All beta drivers to be supported automatically.
- [x] [P1] Have reusable components between bblfsh dashboard and gitbase playground.
- [x] [P1] Interactive UAST visualization/manipulation (same as in gitbase playground).

**Comment by marnovo** [comment]
[OKRs Review] Removed:

- [ ] [P2] More work done on the frontend (call gRPC, libuast) instead of backend

**Comment by bzz** [comment]
> Interactive UAST visualization/manipulation (same as in gitbase playground).
> Have reusable components between bblfsh dashboard and gitbase playground.

Are tracked under https://github.com/bblfsh/uast-viewer

All beta drivers are supported and deployed to http://dashboard.bblf.sh/

> [P0] All beta drivers to be supported automatically

Is handled under https://github.com/bblfsh/sdk/issues/253 and drivers will be in dashboard as soon as they are installed on the server

**Comment by dpordomingo** [comment]
About ` [P0] All beta drivers to be supported automatically.` you could take a look at https://github.com/src-d/minutes/pull/259, discussing the feasibility of this sub-task.

In summary:
- The dashboard will automatically list all drivers that are available on the server (when it was deployed, or that were installed later on)
- Drivers are installed everytime the app is deployed using a predefined list of `driver:version` from [src-d/infrastructure/terraform/.../helm-charts.tf](https://github.com/src-d/infrastructure/blob/master/terraform/modules/clusters/public/helm-charts.tf#L31)
- @rporres should confirm if it could be a good idea to deploy the app installing the drivers with `--recommended` option instead of installing fixed version drivers; an alternative that should be also approved by him could be to let the user install drivers from the dashboard.

**Comment by rporres** [comment]
I understand we're talking about public facing dashboard. If that is the case, it is not a good idea to use `recommended` as you can end with different driver versions if you have multiple pods.

**Comment by bzz** [comment]
End of 2018Q2:
 - all done, latest https://github.com/bblfsh/dashboard/releases/tag/v0.6.0 includes all KRs \w https://uast-viewer.bblf.sh etc
